stations:
  - {id: NCC_Washington, lat: 38.9072, lon: -77.0369, ncc: true, capacity: 999}
  - {id: GS_NewYork, lat: 40.7128, lon: -74.0060, capacity: 6}
  - {id: GS_Dallas, lat: 32.7767, lon: -96.7970, capacity: 6}
  - {id: GS_LosAngeles, lat: 34.0522, lon: -118.2437, capacity: 6}
  - {id: GS_Seattle, lat: 47.6062, lon: -122.3321, capacity: 5}
  - {id: GS_London, lat: 51.5074, lon: -0.1278, capacity: 6}
  - {id: GS_Frankfurt, lat: 50.1109, lon: 8.6821, capacity: 6}
  - {id: GS_Madrid, lat: 40.4168, lon: -3.7038, capacity: 5}
  - {id: GS_Tokyo, lat: 35.6762, lon: 139.6503, capacity: 6}
  - {id: GS_Singapore, lat: 1.3521, lon: 103.8198, capacity: 5}
  - {id: GS_Mumbai, lat: 19.0760, lon: 72.8777, capacity: 5}
  - {id: GS_Sydney, lat: -33.8688, lon: 151.2093, capacity: 4}
  - {id: GS_SaoPaulo, lat: -23.5505, lon: -46.6333, capacity: 4}
  - {id: GS_Johannesburg, lat: -26.2041, lon: 28.0473, capacity: 3}
